Feature/ex 2
nikiJava/AndroidAcademyNewsApp pull request #1
Opened 2018-10-05 15:27 UTC by nikiJava

View Exercise 2.

2018-10-09 23:06 UTC, colriot requested changes

2018-10-09 23:06 UTC, colriot commented on app/src/main/res/layout/item_achievement.xml
> +        android:scaleType="fitXY"
Ты точно такой scaleType хочешь?

2018-10-09 23:06 UTC, colriot commented on app/src/main/res/layout/item_avatar.xml
> +<FrameLayout
А зачем обёртка?

2018-10-09 23:06 UTC, colriot commented on app/src/main/res/layout/item_language.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Тоже зачем обёртка?

2018-10-09 23:06 UTC, colriot commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@android:color/black</item>
Что было с цветом не так?

2018-10-09 23:06 UTC, colriot commented on app/src/main/res/values/styles.xml
> +        <item name="titleTextColor">@android:color/white</item>
А не хочешь просто отнаследоваться от правильного `parent`? А точнее просто его (парента) и заюзать

2018-10-09 23:06 UTC, colriot commented on app/src/main/res/values-ru-rRU/strings.xml
> +    <string name="about_me">"Никита - ещё один парнишка, который видит своё будущее в качестве Андройд-разработчика. Неудержимое желание заниматься мобильной разработкой появилось у него всего два го
Проверь опечатки

2018-10-09 23:06 UTC, colriot commented on app/src/main/res/values-ru-rRU/strings.xml
> +    <string name="message_no_email_client">На Вашем телефон отсутствует почтовый клиент</string>
Ошибки

2018-10-10 09:48 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        etMessage.clearFocus();
Если этот EditText единожды уже получил фокус, то каждый раз при повороте экрана открывалась клавиатура, поскольку при восстановлении состояния активити этот EditText получал фокус снова, что раздражало. Нашёл такой костыльный выход.

2018-10-10 09:53 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        String disclaimer = getString(R.string.disclaimer, getString(R.string.full_name));
Да - необходимо было добавить в самом низу экрана подпись.
![image](https://user-images.githubusercontent.com/22838024/46728385-67df2d80-cc8b-11e8-90b0-ba5f92912d71.png)

2018-10-10 10:01 UTC, nikiJava commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@android:color/black</item>
Поскольку стандартно, из объявленной темы приложения, текст у TextView имеет серый цвет. Чтобы у каждого TextView не указывать textColor="@android:color/black", решил сразу данный атрибут задать в теме.

2018-10-11 20:06 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/delegate_adapter/CompositeDelegateAdapter.java
> +            @NonNull SparseArray<IDelegateAdapter> typeToAdapterMap) {
Ошибка - забыл отформатировать. В студии стоит форматирование, согласно которому аргументы метода переносятся на следующую строку, если не умещаются. Видимо, в какой-то момент не всё на одной строке помещалось.

2018-10-11 20:07 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/domain/BrowserInteractor.java
> +public class BrowserInteractor {
Решил вынести общую логику по открытию ссылки в браузере в отдельный класс. Название позаимствовал из Clean Architecture. Посчитал, что задача, которую выполняет данный класс, укладывается в понятие Interactor.

2018-10-11 20:10 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        contactAdapter = new CompositeDelegateAdapter.Builder<Item>()
На тот случай, если понадобится добавить новый тип элемента. Можно потом просто написать новый адаптер с вьюхолдером и передать их в CompositeDelegateAdapter.

2018-10-11 20:10 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/decorations/Divider.java
> +    public Divider() {
Убрал - он и правда там не нужен был.

2018-10-11 20:37 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        languageRepository = new LanguageRepository(
Вынес в базовый класс.

2018-10-11 20:59 UTC, nikiJava commented on app/src/main/res/layout/item_language.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
На тот случай, если потребуется к айтему добавить ещё какую-либо view (например, ImageView, которая будет отображать айтем как selected, или просто иконку с флагом).

2018-10-11 20:59 UTC, nikiJava commented on app/src/main/res/layout/item_avatar.xml
> +<FrameLayout
На тот случай, если потребуется к аватару добавить ещё какую-либо view (например, подпись).

2018-10-13 17:06 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/delegate_adapter/CompositeDelegateAdapter.java
> +            @NonNull SparseArray<IDelegateAdapter> typeToAdapterMap) {
Поправил.

2018-10-13 17:19 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/LanguagesActivity.java
> +                .add(new ItemLanguageAdapter(this))
Решил придерживаться одного подхода к заполнению RecyclerView данными. Да и код читать легче, когда везде придерживаешься одного подхода (как с архитектурой).

2018-10-13 17:41 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/LanguagesActivity.java
> +        languages.add(new Language(supportedLanguages[0], LanguageLocale.RUSSIAN));
Избавился от подобного массива - языки разнёс по отдельным константам.

2018-10-13 18:01 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/adapter/ItemLanguageAdapter.java
> +    protected ItemLanguageViewHolder createViewHolder(final View parent) {
Поправил - все аргументы методов исправил на final.

2018-10-13 18:33 UTC, nikiJava commented on app/src/main/res/values/styles.xml
> +        <item name="titleTextColor">@android:color/white</item>
Для тулбара добавил атрибут android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar", что позволило сделать title белым. Старый стиль для тулбара удалил.

2018-10-14 22:08 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/LanguagesActivity.java
> +                .add(new ItemLanguageAdapter(this))
А с другой стороны лишние абстракции, когда они не нужны функционально, порождают лишний шум и, наоборот, усложняют код для чтения. Композит намекает, что, будет использовано несколько дочерних адаптеров, поэтому начинаешь автоматом их искать, не потерялись ли и тд. Код собой должен доносить смысл происходящего и быть понятным. А тут лишняя путаница привносится. Не говоря уже о том, что ты добавляется лишние проверки и логику, там, где это может работать быстрее (не про этот код пример, а в целом)

2018-10-14 22:11 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        etMessage.clearFocus();
Выглядит довольно верно - если ты ткнул в эдит, значит захотел что-то написать, а раз захотел сам, то при перевороте не нужно отнимать у тебя такую возможность, особенно, если ты писал как раз.
Получает ли эдит фокус автоматом при открытии экрана?

2018-10-14 22:14 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        contactAdapter = new CompositeDelegateAdapter.Builder<Item>()
Это из разряда premature оптимизаций обычно: http://wiki.c2.com/?PrematureOptimization
Общий совет такой: если что-то пишешь без чёткого понимания, что это надо будет расширять очень скоро, то пиши самым простым и понятным способом. Не усложняй просто так - лишний способ посадить ошибок.

Именно поэтому и был вопрос выше: нигде не используется больше одного viewType, зато везде уже композит.

2018-10-14 22:15 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        contactAdapter = new CompositeDelegateAdapter.Builder<Item>()
Конкретно здесь в задании предлагалось добавить ещё один тип элемента для какой-то категории, отличный от прочих. Вот как раз можешь и реально заюзать композит.

Но тут у меня вопрос: а ты писать руками адаптеры с несколькими вьютайпами до этого?

2018-10-14 22:16 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/adapter/ItemLanguageAdapter.java
> +    protected ItemLanguageViewHolder createViewHolder(final View parent) {
Гут. Но вообще, на аргументы не так уж и обязательно лепить `final`) Главное понимать, зачем ты это делаешь.

2018-10-14 22:17 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/decorations/Divider.java
> +    public Divider() {
В Java пустой конструктор есть по умолчанию, если ты не определил отличный от него.

2018-10-14 22:19 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        String disclaimer = getString(R.string.disclaimer, getString(R.string.full_name));
👍

2018-10-14 22:31 UTC, colriot requested changes

2018-10-14 22:31 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        contactAdapter = new CompositeDelegateAdapter.Builder<Item>()
Пардон, перепутал экраны: тут конкретно такой вопрос: это экран без динамического контента - он фиксирован (его значения и набор элементов). Плюс, список короткий, т.е ресайклинга (переиспользования) тут нет. Т.е это не список-то вовсе, это просто экран, который не влезает в экран на мелких девайсах. Если бы ты реально писал там 10 ачивок, 5 блоков "о себе", 15 соцсеток, то это имело бы смысл. А так это лишняя работа - ты пытаешься сделать максимально расширяемым то место, которое очень маловероятно будет расширяться, пишешь его абстрактно и тд. А по факту просто тратишь время на задачу, которую можно очень быстро решить просто сверстав. Так бы это выглядело в реальном рабочем проекте)

2018-10-14 22:31 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        contactAdapter = new CompositeDelegateAdapter.Builder<Item>()
А композит в списке новостей отлично сможешь заюзать ;)
Ты, кстати, до этого писал адаптеры с несколькими вьютайпами руками?

2018-10-14 22:31 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        rvContacts.offsetChildrenVertical((int) getResources().getDimension(R.dimen.offset_item));
Здесь можно было паддинг просто заюзать, мне кажется

2018-10-14 22:31 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/decorations/Divider.java
> +    public static synchronized Divider getInstance() {
Если делать синглтоном, то можно было его проинициализировать сразу `static` полем. Он легкий и просто, незачем делать отложенную инициализацию. А ещё это UI-штука, только в UI используется. Т.е синхронизация лишняя - она ведь тоже не бесплатная, а раз не нужна, то и убрать стоит.

2018-10-14 22:37 UTC, colriot requested changes

2018-10-14 22:37 UTC, colriot commented on app/build.gradle
> +    implementation fileTree(include: ['*.jar'], dir: 'libs')
Не вижу, чтобы в коде что-то поменялось. А отмечено, как resolved...

2018-10-14 22:37 UTC, colriot commented on app/build.gradle
> +    implementation 'com.android.support:recyclerview-v7:28.0.0'
Версия у всех саппортных либ одна и та же - можно вынести в переменную. Как в примере из 3 лекции.

2018-10-14 22:37 UTC, colriot commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
А процессор точно нужен?

2018-10-14 22:37 UTC, colriot commented on app/build.gradle
> +
Пустые строки лишние

2018-10-14 22:37 UTC, colriot commented on app/src/main/AndroidManifest.xml
> +        android:fullBackupContent="false"
Это зачем? Может лучше просто `allowBackup` в `false` поменять?

2018-10-14 22:37 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/AndroidAcademyNewsApp.java
> +
Снова помечено как resolved?

2018-10-15 08:03 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        etMessage.clearFocus();
Да, получает, к сожалению. Видимо, при повороте экрана, когда активити свой стейт сохраняет, она в том числе сохраняет информацию и о том, какая view бала в фокусе. Пробовал различные трюки, для того, чтобы фокус получала какая-либо другая view, которая находятся выше по иерархии, но бесполезно.

2018-10-15 08:16 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        contactAdapter = new CompositeDelegateAdapter.Builder<Item>()
Если имеет ввиду, делал ли адаптер с несколькими viewType без делегатов, то да, на первых парах так и делал, что приводило к сильному наводнения адаптера ресайклера кодом в большом количестве(( Потом уже для себя делегаты открыл, но по-другому их делал. Потом открыл для себя эту статейку https://habr.com/post/341738/ (в readme её прикрепил) и решил сразу опробовать, потому что заранее знал, что в приложении будут неоднородные списки.

2018-10-15 08:17 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/adapter/ItemLanguageAdapter.java
> +    protected ItemLanguageViewHolder createViewHolder(final View parent) {
Я привык, что в котлине аргументы идут как final из коробки и это очень удобно - меньше ошибок можешь насовершать. Решил подобного подхода придерживаться и в java.

2018-10-18 14:47 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        etMessage.clearFocus();
Так я же выше и написал, что это нормальное поведение - если ты писал до поворота, то стейт должен сохраниться и после поворота. Если не писал, и клавы не было, то и не должно быть после поворота.

2018-10-18 15:00 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/adapter/ItemLanguageAdapter.java
> +    protected ItemLanguageViewHolder createViewHolder(final View parent) {
В Java хорошо бы делать`final` поля классов, а вот ещё и все аргументы делать `final` - это очень многословно. В большинстве реальных проектов на это забивают. Имхо, хороший пример организации кода - библиотеки Square. И там они не делают аргументы `final`

2018-10-18 15:36 UTC, nikiJava commented on app/src/main/AndroidManifest.xml
> +        android:fullBackupContent="false"
Ошибся с нужным атрибутом. Поправил.

2018-10-18 16:18 UTC, nikiJava commented on app/build.gradle
> +
Поправил.

2018-10-18 16:30 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/viewholders/ItemContactViewHolder.java
> +        ivContact.setOnClickListener(v -> {
Поправил.

2018-10-18 16:36 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        etMessage.clearFocus();
Похоже, что я не совсем точно описал проблему))) Смотрите - по клику на EditText клавиатура открывается, затем по кнопке back я её скрываю и на экране клавиатуры более нет. Затем поворачиваю экран и клавиатура снова открывается. Поэтому добавил подобный костыль.

2018-10-19 10:53 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        rvContacts.offsetChildrenVertical((int) getResources().getDimension(R.dimen.offset_item));
На экране визитки заменил композит на статическую вёрстку.

2018-10-19 10:55 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/LanguagesActivity.java
> +                .add(new ItemLanguageAdapter(this))
Убрал экран для изменения языка. Займусь им позднее.

2018-10-22 13:17 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        etMessage.clearFocus();
А, это происходит, потому что фокус всё равно остался в `EditText`. Проблема в том, что у тебя и в мною описанной кейсе будет скрываться клава, хотя не особо должна. Но оставляй, если "таковы бизнес-требования" =)

2018-10-22 13:17 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        contactAdapter = new CompositeDelegateAdapter.Builder<Item>()
Да, здесь это логично

2018-10-22 13:20 UTC, colriot commented on app/src/main/res/layout/activity_main.xml
> +                android:inputType="text"
Я скорее про `textCapSentences` и тд. Чтобы оно более удобно было для ввода текстов

2018-10-22 13:23 UTC, colriot commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@android:color/black</item>
Я в прошлую нашу встречу говорил про стили текста. Так вот он у тебя тут серый, потому что используется стиль по умолчанию и там `textColorSecondary`. Либо попробуй другой стиль (`textAppearance`) для текста, либо возьми цвет `?textColorPrimary`, а не прям чёрный. Чтобы этот цвет менялся в зависимости от глобальной темы приложения.

2018-10-22 13:24 UTC, colriot requested changes
Ещё несколько замечаний есть

2018-10-22 18:19 UTC, nikiJava commented on app/src/main/res/layout/app_bar.xml
> +<merge
Согласен, merge здесь явно оказался лишним.

2018-10-22 18:42 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +    private void recomputeAvatarSize() {
params.height = (int) (layoutPosition * 0.4)

Хотел добиться того, чтобы аватарка занимала всегда 40%  от экрана на всех устройствах. Из-за того, что для перерасчёта dp в px используются ограниченный набор коэффициентов, на некоторых смартфонах может уместиться меньше контента). А так, аватарка всегда занимает строго заданную долю от высоты экрана (от полезной высоты экрана, которая не включает в себя тулбар и статус бар).

2018-10-25 11:30 UTC, colriot reviewed
Пару моментов осталось. И можешь ещё скриншоты экранов по этому домашке прикрепить к PR, плз. В разных ориентациях

2018-10-25 11:30 UTC, colriot commented on app/src/main/res/layout/activity_main.xml
> +            <ImageView
Тут все те же вопросы

2018-10-25 11:30 UTC, colriot commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginEnd">@dimen/standard_margin</item>
Не забывай форматировать код - атрибуты выстроятся по алфавиту/правилам

2018-10-25 11:30 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +    private void recomputeAvatarSize() {
1) Статусбар не всегда 24dp. 
2) Для твое задачи лучше брать не весь экран, а размеры парента - твоего LL, который точно расположен под статусбаром и тулбаром. И от него уже считать проценты.
3) Там точно не надо обратно сеттить новые парамсы через `setLayoutParams`?

Но опять-таки, это всё сложно. Почему нельзя просто задать у аватара `layout_weight=0.4`, а у скроллвью `0.6`?

2018-10-25 11:30 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +             .apply(RequestOptions.overrideOf(avatarWidth, avatarHeight))
Библиотека сама берёт текущие размеры `IV` и использует их для ресайза, не надо это делать руками в твоём случае

2018-10-25 11:30 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        tvAchievementWellmarkName.setOnClickListener(v -> ivAchievementWellmarkIcon.callOnClick());
Это плохой метод по двум причинам:
1) У тебя два разных контрола, которые по сути являются одни целым (единой кнопкой) - у них должна быть общая индикация нажатия (нажатый фон), независимо от того, на кого из них кликнули, общая обработка клика (например, заморозка кнопкки, пока идёт запрос в сеть, чтобы много раз не накликивали) и тд. Т.е в таких случаях лучше обернуть это все в одну из простых `ViewGroup` и на неё навесить все атрибуты и настройки кликов (как у тебя и было до этого, поэтому, если считаешь, что какие-то мои комментарии неверны, или ты не понимаешь, почему так надо сделать, лучше сперва спросить, потому что у меня нет полного понимания твоей задумки при проведении CR, т.е я могу что-то упустить тоже :)).
2) Но в твоём случае, это IV и TV, стоящие рядом. IV со статической иконкой. Т.е можно юзать `drawable*` у TV (здесь `drawableStart`). Об этом на прошлой нашей очной встрече говорили. Или с этим были проблемы?

2018-10-25 11:30 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        tvAchievementWellmarkName.setOnClickListener(v -> ivAchievementWellmarkIcon.callOnClick());
3. Не стоит дёргать так чужие обработчики. Лучше, если вынужден будешь так сделать, то ставь одинаковые листнеры сам (инкапсулированные в один метод).

2018-10-29 14:19 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        tvAchievementWellmarkName.setOnClickListener(v -> ivAchievementWellmarkIcon.callOnClick());
1 и 3 - объединил вьюшки ivAchievementWellmarkIcon и tvAchievementWellmarkName в целостный item (собственно, вернул, как было).
2 - действительно возникли проблемы - использовал drawableStart - в результате drawable игнорирует размеры TextView.
![image](https://user-images.githubusercontent.com/22838024/47655696-a1c29600-db9e-11e8-8a56-0b6cc08209e3.png)

2018-10-29 15:24 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +             .apply(RequestOptions.overrideOf(avatarWidth, avatarHeight))
3 - новые params сеттить не нужно;

2 и "Но опять-таки, это всё сложно. Почему нельзя просто задать у аватара layout_weight=0.4, а у скроллвью 0.6?" - у меня аватар находится внутри RelativeLayout, а тот уже внутри ScrollView. Непосредственно сам RelativeLayout не имеет атрибутов weight. Если обрамлять весь контент в дополнительный/-ые LinearLayout/-ы, получим дополнительную вложенность. Да и результата не даст, так как при weight берётся в расчёт непосредственно размер родителя (самого LinearLayout), который по итогу может превышать размер экрана смартфона. В итоге нашёл такое решение, которое и привёл в упражнении.

2018-10-29 15:27 UTC, nikiJava commented on app/src/main/res/layout-land/activity_main.xml
> +                    android:background="@drawable/logo_work_cropped"
1 - судя по всему, когда отлавливал какую-то проблему, забыл исправить обратно на правильный атрибут.
2 - действительно возникли проблемы - использовал drawableStart - в результате drawable игнорирует размеры TextView.
![image](https://user-images.githubusercontent.com/22838024/47660510-354c9480-dba8-11e8-99a3-019f740805a7.png)

2018-10-29 15:29 UTC, nikiJava commented on app/src/main/res/layout/activity_main.xml
> +            <ImageView
Здесь не совсем понял, что нужно исправить...

2018-10-29 20:00 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
> +                    android:background="@drawable/logo_work_cropped"
А какого размера сам drawable?

2018-10-29 20:02 UTC, colriot commented on app/src/main/res/layout/activity_main.xml
> +            <ImageView
Тоже `background` юзается, и тоже можно `drawableStart` заюзать

2018-10-29 20:04 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        tvAchievementWellmarkName.setOnClickListener(v -> ivAchievementWellmarkIcon.callOnClick());
Я думаю, что мы всё таки разберёмся c `drawableStart` =)

2018-10-29 20:20 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
> +                    android:background="@drawable/logo_work_cropped"
Конечно, всё происходит потому, что у тебя неспецифицированы размеры иконки. Она лежит в папке `drawable`, там (на текущий момент) должны лежать только xml-ные картинки, потому что у них явно заданы размеры в xml. А у рисованных картинок размеры - это их собственные, с учётом dpi. У тебя же они лежат без учёта dpi. Это не по феншую - нужно иметь отдельные варианты для разных dpi экранов: hdpi, xhdpi и тд. И чтобы сама картинка была размера 24dp x 24dp. Тогда у тебя всё нормально будет выглядеть в `drawableStart`.

2018-10-29 20:21 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        tvAchievementWellmarkName.setOnClickListener(v -> ivAchievementWellmarkIcon.callOnClick());
Выше описал твою проблему и как её решить.

2018-10-29 20:30 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +             .apply(RequestOptions.overrideOf(avatarWidth, avatarHeight))
LL, который я имел в виду, это тот, который расположен под статусбаром и тулбаром, а не непосредственный парент. Проверил, к сожалению, он есть только в `land`-разметке, но сути это не меняет - в дефолтной это будет сам NestedScrollView и его размеры. В общем, тебе нужно не окно (Window, в котором куча прочих элементов), а кусок твоей разметки, который рисуется на всю активити (кроме Тулбара), и размеры которого как раз и являются тем прямоугольников, от которого ты отсчитываешь проценты.

А про `layout_weight` комментарий был к тому, что если ты будешь использовать drawableStart, то тебе не нужен будет RL, достаточно будет только LL. Но ты верно говоришь, что LL будет в высоту больше экрана, тут я проглядел.

2018-10-29 21:09 UTC, colriot reviewed
Добавил комментариев

2018-10-29 21:09 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
> +                    style="@style/DividerStyle"
Вообще мне эта разметка не кажется удачной.
1) Если ты в итоге заюзаешь `drawableStart` на TextView, то RL можно будет заменить на LL вертикальный.
2) А значит убрать всё `id` из divider-ов и `layout_below` и тд. Также непонятно, зачем стиль дивайдерам указывать везде отдельно, когда можно указать его в самом `@layout/divider`. И тогда `include`-ы превратятся в одну строчку
3) `marginStart` у тебя вроде везде одинаковый, тогда лучше вместо его дублирования множественного задать `padding` у парента?
4) `FrameLayout` со стилями `ContactStyle.ItemLayout` - это что за велосипед?) У тебя там два IV друг на друге, у одного `background` задан, у другого `srcCompat`. А в чем проблема задать оба атрибута у одного IV?
5) По-моему куски с инфой о тебе примерно одинаковые в альбомной и портретной ориентации? Так вынеси их в отдельный лайаут (о чем говорили на одной из встречь) и лишь единожды его напиши, исправь все косяки и останется только  заинклюдить его в нужные места разметок для альбомной и портретной ориентации.

2018-10-29 21:09 UTC, colriot commented on app/src/main/res/values-ru-rRU/strings.xml
> +<?xml version="1.0" encoding="utf-8"?>
Не надо зашиваться и на язык, и на страну. Переименую папку в `values-ru`, чтобы при выборе русского языка использовалась эта локаль всегда. Не только в России, но и в Беларуси, в Казахстане и тд

2018-10-29 21:09 UTC, colriot commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@android:color/black</item>
Помечено как resolved. Что-то изменилось?

2018-10-29 21:09 UTC, colriot commented on app/src/main/res/layout/item_avatar.xml
> +<FrameLayout
А тут что исправлено?

2018-10-29 21:09 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +    private void recomputeAvatarSize() {
А ещё ты не под тем комментом ответил

2018-11-03 20:51 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        tvAchievementWellmarkName.setOnClickListener(v -> ivAchievementWellmarkIcon.callOnClick());
Решилось переносом картинки в папку drawable-xxxhdpi.

2018-11-03 21:08 UTC, nikiJava commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +             .apply(RequestOptions.overrideOf(avatarWidth, avatarHeight))
Убрал получение через Window. Сделал пересчёт высоты аватары через NestedScrollView - всё работает. Сделал через post(), потому что на момент пересчёта вьюшка ещё не отрисована, а post позволил исполнить этот код уже после отрисовки вьюшки. 
private void recomputeAvatarSize() {
         svContent.post(() -> {
             float layoutPosition = svContent.getHeight();
             LinearLayout.LayoutParams params =
                     (LinearLayout.LayoutParams) ivAvatar.getLayoutParams();
             params.height = (int) (layoutPosition * 0.4);
        });
    }

2018-11-04 10:18 UTC, nikiJava commented
Скриншоты:

![image](https://user-images.githubusercontent.com/22838024/47962859-fdc06b00-e033-11e8-9574-454c641ece29.png)

![image](https://user-images.githubusercontent.com/22838024/47962853-f00ae580-e033-11e8-865d-f2ea366cf714.png)

2018-11-05 10:19 UTC, nikiJava commented on app/src/main/res/values-ru-rRU/strings.xml
> +<?xml version="1.0" encoding="utf-8"?>
Переименовал папку в values-ru.

2018-11-05 16:55 UTC, colriot reviewed
Собрал оставшиеся замечания

2018-11-05 16:55 UTC, colriot commented on app/src/main/res/layout-land/activity_main.xml
> +                    layout="@layout/item_about"
Не надо разбирать на такие миниатюрные кусочки. Выделить стоило всю общую часть вместе в отдельный layout, но не нарезать на части.

2018-11-05 16:55 UTC, colriot commented
Ну и плюс `textAppearance`

2018-11-11 13:31 UTC, nikiJava commented on app/src/main/res/layout-land/activity_main.xml
> +                    layout="@layout/item_about"
Выделил общую часть в отдельный layout.

2018-11-11 15:45 UTC, colriot commented on app/src/main/java/ru/nikijava/androidacademynewsapp/presentation/MainActivity.java
> +        TextViewCompat.setTextAppearance(tvDisclaimer, R.style.TextAppearance_Disclaimer);
👍

2018-11-11 15:45 UTC, colriot commented on app/src/main/res/layout/layout_about_content.xml
> +        android:textAppearance="@style/TextAppearance.Achievement"
Не забывай форматировать код - будет единообразная сортировка атрибутов.

2018-11-11 15:45 UTC, colriot commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColorPrimary">@android:color/black</item>
Повторю один момент:
`textColorPrimary` и аналогичные - это атрибуты Темы, т.е. ты их можешь поменять для всего приложения (есть исключения, но сейчас не суть),
а `@style/TextAppearance.AppCompat.Body1` - это Стиль, т.е он применяется там, где ты установишь этот стиль.
Если у тебя светлая тема, то `textColorPrimary` и так будет чёрным.
А если ты хочешь изменить цвет у какого-то text appearance, то надо изменить атрибут от text appearance - `textColor`. Но только у `TextAppearance.AppCompat.Body1` и так чёрный цвет текста тоже, потому что там `?textColorPrimary` значение юзается.

2018-11-12 12:09 UTC, colriot approved these changes

2018-11-16 16:22 UTC, merged